opt_in_rules:
  - empty_count
  - force_unwrapping

file_length:
  warning: 500
  error: 1000

line_length: 120

type_name:
  max_length:
    warning: 50
    error: 60
  min_length:
    warning: 1

variable_name:
  max_length:
    warning: 50
    error: 60
  min_length:
    warning: 1

nesting:
  type_level:
    warning: 5
  statement_level:
    warning: 10

type_body_length:
  warning: 300
  error: 400

excluded:
  - Pods
  - Carthage
  - Frameworks

reporter: "xcode"